<Finish>:
	name: "Finish"
	canvas.before:
		Color:
			rgba: dark_blue
		Rectangle:
			pos: self.pos
			size: self.size
	BoxLayout:
		orientation: 'vertical'
		Label:
			font_size: self.height * 0.4
			color: light_blue
			text: 'ZAKOŃCZONO'
		AnchorLayout:
			anchor_x: 'center'
			anchor_y: 'center'
			OrangeButton:
				size_hint: 0.5, 0.5
				text: 'MENU'
				font_size: self.height * 0.3
				on_release: root.go_to_menu()
